### ISSUE TITLE
Removing duplicate entries (aliases)

### ISSUE THREAD

**Issue by oatmealm** [publicimageltd/org-roam-dashboard#1]
Thanks a lot for this module! Love it.

Wondering if this is by design or not: the dashboard will show same entry under all of its aliases, like so:

![gnome-shell-screenshot-T83JR0](https://user-images.githubusercontent.com/68159077/94178896-01657100-fe9c-11ea-8d66-56735e9f4d6d.png)

The entry has the following aliases and thus is shown 5 times.

```
#+roam_alias: "جماعة الإخوان المسلمين" "Muslim Brotherhood" "אגודת האחים המוסלמים" "האחים המסלמים"

```

**Comment by publicimageltd** [comment]
That's an interesting bug. I didn't even know that it is possible to create an alias. I'll have to investigate that. Unfortunately, I have already moved to another project which will supersede the dashboard. It is much cleaner written and has a more flexible user interface, but it is not on github yet. So I guess I will check out the alias thing with the new program and post here once it's online.

**Comment by oatmealm** [comment]
@publicimageltd  that's interesting to hear! Looking forward to see what you come up with :)
